"""empty message

Revision ID: 31239bb2d0d4
Revises: 32aecfda045e
Create Date: 2024-06-14 06:18:37.805848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31239bb2d0d4'
down_revision = '32aecfda045e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_table', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
