"""empty message

Revision ID: 8b86ae66d485
Revises: 31239bb2d0d4
Create Date: 2024-06-14 06:24:13.926740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b86ae66d485'
down_revision = '31239bb2d0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_table', schema=None) as batch_op:
        batch_op.alter_column('invoice_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_table', schema=None) as batch_op:
        batch_op.alter_column('invoice_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
